"""alter description fields to Text

Revision ID: 21890f8ea6b9
Revises: 17bdcaac8ee6
Create Date: 2025-09-29 01:43:47.500337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21890f8ea6b9'
down_revision = '17bdcaac8ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
